const mockMovies = [
  {
    _id: "movie1",
    title: "Inception",
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    genre: ["Sci-Fi", "Action", "Thriller"],
    language: "English",
    duration: 148,
    releaseDate: "2010-07-16",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    poster: "https://picsum.photos/400/600?random=1",
    rating: 9.0,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    isRecommended: true,
    similarMovies: ["movie2", "movie3"],
    reviews: [
      { user: "Priya", rating: 5, comment: "Wah! Kya movie hai! Mind-blowing!", date: "2023-05-20" },
      { user: "Rahul", rating: 4, comment: "Badiya visuals! Must watch!", date: "2023-06-10" }
    ]
  },
  {
    _id: "movie2",
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    genre: ["Action", "Crime", "Drama"],
    language: "English",
    duration: 152,
    releaseDate: "2008-07-18",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    poster: "https://picsum.photos/400/600?random=2",
    rating: 9.0,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    isRecommended: true,
    similarMovies: ["movie1", "movie7"],
    reviews: [
      { user: "Arjun", rating: 5, comment: "Heath Ledger ne kamaal kar diya! Legendary performance!", date: "2023-04-15" }
    ]
  },
  {
    _id: "movie3",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    language: "English",
    duration: 169,
    releaseDate: "2014-11-07",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    poster: "https://picsum.photos/400/600?random=3",
    rating: 8.6,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    isRecommended: true,
    similarMovies: ["movie1", "movie5"],
    reviews: []
  },
  {
    _id: "movie4",
    title: "Avatar: The Way of Water",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    genre: ["Action", "Adventure", "Fantasy"],
    language: "English",
    duration: 192,
    releaseDate: "2022-12-16",
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    trailer: "https://www.youtube.com/embed/d9MyW72ELq0",
    poster: "https://picsum.photos/400/600?random=4",
    rating: 7.8,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    isRecommended: true,
    similarMovies: ["movie3", "movie5"],
    reviews: []
  },
  {
    _id: "movie5",
    title: "Dune: Part Two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    duration: 166,
    releaseDate: "2024-03-01",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    trailer: "https://www.youtube.com/embed/Way9Dexny3w",
    poster: "https://picsum.photos/400/600?random=5",
    rating: 8.8,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie3", "movie4"],
    reviews: []
  },
  {
    _id: "movie6",
    title: "Avengers: Secret Wars",
    description: "An epic conclusion to the Multiverse Saga.",
    genre: ["Action", "Sci-Fi", "Fantasy"],
    language: "English",
    duration: 180,
    releaseDate: "2027-05-07",
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    trailer: "https://www.youtube.com/embed/eOrNdBpGMv8",
    poster: "https://picsum.photos/400/600?random=6",
    rating: 0,
    isTrending: false,
    isUpcoming: true,
    isComingSoon: true,
    comingSoonDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    similarMovies: ["movie5", "movie4"],
    reviews: []
  },
  {
    _id: "movie7",
    title: "The Batman",
    description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    genre: ["Action", "Crime", "Drama"],
    language: "English",
    duration: 176,
    releaseDate: "2022-03-04",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
    trailer: "https://www.youtube.com/embed/mqqft2x_Aa4",
    poster: "https://picsum.photos/400/600?random=7",
    rating: 7.8,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie2", "movie1"],
    reviews: []
  },
  {
    _id: "movie8",
    title: "Spider-Man: Beyond the Spider-Verse",
    description: "The next chapter in the Spider-Verse saga.",
    genre: ["Animation", "Action", "Adventure"],
    language: "English",
    duration: 140,
    releaseDate: "2025-06-27",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    trailer: "https://www.youtube.com/embed/cqGjhVJWtEg",
    poster: "https://picsum.photos/400/600?random=8",
    rating: 0,
    isTrending: false,
    isUpcoming: true,
    isComingSoon: true,
    comingSoonDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    similarMovies: ["movie6", "movie5"],
    reviews: []
  },
  {
    _id: "movie9",
    title: "Oppenheimer",
    description: "The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.",
    genre: ["Biography", "Drama", "History"],
    language: "English",
    duration: 180,
    releaseDate: "2023-07-21",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    trailer: "https://www.youtube.com/embed/uYPbbksJxIg",
    poster: "https://picsum.photos/400/600?random=9",
    rating: 8.8,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie3", "movie1"],
    reviews: []
  },
  {
    _id: "movie10",
    title: "Barbie",
    description: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover that the joy isn't all it's cracked up to be.",
    genre: ["Comedy", "Fantasy", "Adventure"],
    language: "English",
    duration: 114,
    releaseDate: "2023-07-21",
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera"],
    trailer: "https://www.youtube.com/embed/pBk4NYhWNKM",
    poster: "https://picsum.photos/400/600?random=10",
    rating: 7.0,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie11", "movie12"],
    reviews: []
  },
  {
    _id: "movie11",
    title: "Jurassic World: Dominion",
    description: "Four years after the destruction of Isla Nublar, dinosaurs live and hunt alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history's most fearsome creatures.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    duration: 147,
    releaseDate: "2022-06-10",
    cast: ["Chris Pratt", "Bryce Dallas Howard", "Laura Dern"],
    trailer: "https://www.youtube.com/embed/fb5ELWi-ekk",
    poster: "https://picsum.photos/400/600?random=11",
    rating: 5.6,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie4", "movie10"],
    reviews: []
  },
  {
    _id: "movie12",
    title: "Top Gun: Maverick",
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
    genre: ["Action", "Drama"],
    language: "English",
    duration: 130,
    releaseDate: "2022-05-27",
    cast: ["Tom Cruise", "Jennifer Connelly", "Miles Teller"],
    trailer: "https://www.youtube.com/embed/giXco2jaZ_4",
    poster: "https://picsum.photos/400/600?random=12",
    rating: 8.3,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie1", "movie2"],
    reviews: []
  },
  {
    _id: "movie13",
    title: "Mission: Impossible - Dead Reckoning Part One",
    description: "Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity if it falls into the wrong hands. With control of the future and the fate of the world at stake, a deadly race around the globe begins.",
    genre: ["Action", "Adventure", "Thriller"],
    language: "English",
    duration: 163,
    releaseDate: "2023-07-12",
    cast: ["Tom Cruise", "Hayley Atwell", "Ving Rhames"],
    trailer: "https://www.youtube.com/embed/avz06PDqDbM",
    poster: "https://picsum.photos/400/600?random=13",
    rating: 8.1,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie12", "movie2"],
    reviews: []
  },
  {
    _id: "movie14",
    title: "Dangal",
    description: "Former wrestler and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.",
    genre: ["Drama", "Biography", "Sport"],
    language: "Hindi",
    duration: 161,
    releaseDate: "2016-12-23",
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra"],
    trailer: "https://www.youtube.com/embed/x_7YlG5WhRA",
    poster: "https://picsum.photos/400/600?random=14",
    rating: 8.3,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: [],
    reviews: [
      { user: "Sneha", rating: 5, comment: "Aamir Khan ji ne dil jeet liya! Desh ke liye proud feel hota hai!", date: "2023-08-22" },
      { user: "Raj", rating: 5, comment: "Betiyon ka samman! Kya movie banayi hai!", date: "2023-09-05" }
    ]
  },
  {
    _id: "movie15",
    title: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating the High Table while facing powerful enemies around the world.",
    genre: ["Action", "Crime", "Thriller"],
    language: "English",
    duration: 169,
    releaseDate: "2023-03-24",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    trailer: "https://www.youtube.com/embed/qEVUtrk8_B4",
    poster: "https://picsum.photos/400/600?random=15",
    rating: 8.2,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie13", "movie14"],
    reviews: []
  },
  {
    _id: "movie16",
    title: "Amélie",
    description: "Amélie, an innocent and naive girl in Paris, with her own sense of justice, decides to help those around her and, along the way, discovers love.",
    genre: ["Comedy", "Romance", "Fantasy"],
    language: "French",
    duration: 122,
    releaseDate: "2001-04-25",
    cast: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus"],
    trailer: "https://www.youtube.com/embed/2UT5xaAfxWU",
    poster: "https://picsum.photos/400/600?random=16",
    rating: 8.3,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: [],
    reviews: []
  },
  {
    _id: "movie17",
    title: "Guardians of the Galaxy Vol. 3",
    description: "The Guardians embark on one last mission to save one of their own.",
    genre: ["Action", "Adventure", "Comedy"],
    language: "English",
    duration: 150,
    releaseDate: "2023-05-05",
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    trailer: "https://www.youtube.com/embed/u3V5KDHRQvk",
    poster: "https://picsum.photos/400/600?random=17",
    rating: 8.0,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie5", "movie6"],
    reviews: []
  },
  {
    _id: "movie18",
    title: "Deadpool & Wolverine",
    description: "Deadpool teams up with Wolverine on a multiversal adventure.",
    genre: ["Action", "Comedy", "Sci-Fi"],
    language: "English",
    duration: 127,
    releaseDate: "2024-07-26",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    trailer: "https://www.youtube.com/embed/73_1biulkYk",
    poster: "https://picsum.photos/400/600?random=18",
    rating: 8.0,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie16", "movie19"],
    reviews: []
  },
  {
    _id: "movie19",
    title: "Run Lola Run",
    description: "Lola has 20 minutes to get 100,000 Deutsche Mark to save her boyfriend Manni's life.",
    genre: ["Action", "Crime", "Thriller"],
    language: "German",
    duration: 81,
    releaseDate: "1998-08-20",
    cast: ["Franka Potente", "Moritz Bleibtreu", "Herbert Knaup"],
    trailer: "https://www.youtube.com/embed/W9XU5b62eW4",
    poster: "https://picsum.photos/400/600?random=19",
    rating: 7.7,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: [],
    reviews: []
  },
  {
    _id: "movie20",
    title: "Black Panther: Wakanda Forever",
    description: "The leaders of Wakanda fight to protect their nation after King T'Challa's death.",
    genre: ["Action", "Adventure", "Drama"],
    language: "English",
    duration: 161,
    releaseDate: "2022-11-11",
    cast: ["Letitia Wright", "Lupita Nyong'o", "Angela Bassett"],
    trailer: "https://www.youtube.com/embed/_Z3QKkl1WyM",
    poster: "https://picsum.photos/400/600?random=20",
    rating: 6.7,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie16", "movie6"],
    reviews: []
  },
  {
    _id: "movie21",
    title: "Doctor Strange in the Multiverse of Madness",
    description: "Doctor Strange journeys through the multiverse with a mysterious new ally.",
    genre: ["Action", "Adventure", "Fantasy"],
    language: "English",
    duration: 126,
    releaseDate: "2022-05-06",
    cast: ["Benedict Cumberbatch", "Elizabeth Olsen", "Xochitl Gomez"],
    trailer: "https://www.youtube.com/embed/aWzlQ2N6qqg",
    poster: "https://picsum.photos/400/600?random=21",
    rating: 6.9,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie6", "movie17"],
    reviews: []
  },
  {
    _id: "movie22",
    title: "The Super Mario Bros. Movie",
    description: "Mario and Luigi are transported to a magical world and must save it from Bowser.",
    genre: ["Animation", "Adventure", "Comedy"],
    language: "English",
    duration: 92,
    releaseDate: "2023-04-05",
    cast: ["Chris Pratt", "Anya Taylor-Joy", "Jack Black"],
    trailer: "https://www.youtube.com/embed/TnGl01FkMMo",
    poster: "https://picsum.photos/400/600?random=22",
    rating: 7.1,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie8", "movie10"],
    reviews: []
  },
  {
    _id: "movie23",
    title: "The Flash",
    description: "Barry Allen travels back in time to prevent a tragedy but alters the future.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    duration: 144,
    releaseDate: "2023-06-16",
    cast: ["Ezra Miller", "Michael Keaton", "Sasha Calle"],
    trailer: "https://www.youtube.com/embed/hebWYacbdvc",
    poster: "https://picsum.photos/400/600?random=23",
    rating: 6.7,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie7", "movie19"],
    reviews: []
  },
  {
    _id: "movie24",
    title: "Pan's Labyrinth",
    description: "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
    genre: ["Drama", "Fantasy", "War"],
    language: "Spanish",
    duration: 118,
    releaseDate: "2006-10-11",
    cast: ["Ivana Baquero", "Ariadna Gil", "Sergi López"],
    trailer: "https://www.youtube.com/embed/jVZRnnVSQ8k",
    poster: "https://picsum.photos/400/600?random=24",
    rating: 8.2,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: [],
    reviews: []
  },
  {
    _id: "movie25",
    title: "Aquaman and the Lost Kingdom",
    description: "Aquaman must forge an alliance with an unlikely ally to save Atlantis.",
    genre: ["Action", "Adventure", "Fantasy"],
    language: "English",
    duration: 124,
    releaseDate: "2023-12-15",
    cast: ["Jason Momoa", "Patrick Wilson", "Amber Heard"],
    trailer: "https://www.youtube.com/embed/FV3bqvOHRQo",
    poster: "https://picsum.photos/400/600?random=25",
    rating: 6.0,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie4", "movie21"],
    reviews: []
  },
  {
    _id: "movie26",
    title: "Transformers: Rise of the Beasts",
    description: "Optimus Prime and the Autobots face a new threat capable of destroying Earth.",
    genre: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    duration: 127,
    releaseDate: "2023-06-09",
    cast: ["Anthony Ramos", "Dominique Fishback", "Peter Cullen"],
    trailer: "https://www.youtube.com/embed/itnqEauWQZM",
    poster: "https://picsum.photos/400/600?random=26",
    rating: 6.4,
    isTrending: false,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie11", "movie14"],
    reviews: []
  },
  {
    _id: "movie27",
    title: "Wonka",
    description: "The story of how the world's greatest inventor and magician became Willy Wonka.",
    genre: ["Adventure", "Comedy", "Fantasy"],
    language: "English",
    duration: 116,
    releaseDate: "2023-12-15",
    cast: ["Timothée Chalamet", "Olivia Colman", "Hugh Grant"],
    trailer: "https://www.youtube.com/embed/otNh9bTjXWg",
    poster: "https://picsum.photos/400/600?random=27",
    rating: 7.0,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    similarMovies: ["movie10", "movie20"],
    reviews: []
  },
  {
    _id: "movie28",
    title: "3 Idiots",
    description: "Three engineering students bond over their struggles, dreams, and a quest to redefine education in India.",
    genre: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
    duration: 170,
    releaseDate: "2009-12-25",
    cast: ["Aamir Khan", "Kareena Kapoor", "R. Madhavan"],
    trailer: "https://www.youtube.com/embed/K0eY9BMSX3g",
    poster: "https://picsum.photos/400/600?random=28",
    rating: 8.4,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    isRecommended: true,
    similarMovies: ["movie14", "movie27"],
    reviews: [
      { user: "Neha", rating: 5, comment: "All is well! Life changing movie!", date: "2023-07-19" },
      { user: "Vikram", rating: 5, comment: "Aamir Khan ne phir se proof kar diya!" }
    ]
  },
  {
    _id: "movie29",
    title: "Bahubali: The Beginning",
    description: "An epic tale of a young man who discovers his royal heritage and must reclaim his kingdom.",
    genre: ["Action", "Adventure", "Fantasy"],
    language: "Telugu",
    duration: 159,
    releaseDate: "2015-07-10",
    cast: ["Prabhas", "Anushka Shetty", "Rana Daggubati"],
    trailer: "https://www.youtube.com/embed/Vdaf7i0nrcI",
    poster: "https://picsum.photos/400/600?random=29",
    rating: 8.0,
    isTrending: true,
    isUpcoming: false,
    isComingSoon: false,
    isRecommended: true,
    similarMovies: ["movie28", "movie14"],
    reviews: [
      { user: "Divya", rating: 5, comment: "Katappa ne Bahubali ko kyun maara? Epic mystery!", date: "2023-10-02" },
      { user: "Karthik", rating: 5, comment: "Visuals ke liye hi dekh lo! Prabhas rocks!" }
    ]
  }
];

const mockTheaters = [
  {
    _id: "theater1",
    name: "CineVerse IMAX",
    location: "Downtown",
    screens: 4
  },
  {
    _id: "theater2",
    name: "CineVerse Premium",
    location: "City Center",
    screens: 3
  }
];

const mockShows = [
  {
    _id: "show1",
    movie: "movie1",
    theater: "theater1",
    date: "2024-01-01",
    time: "10:00 AM",
    price: 15,
    pricePlatinum: 25,
    priceGold: 20,
    priceSilver: 15,
    availableSeats: [
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
    ],
    seatTiers: ["Silver", "Silver", "Gold", "Gold", "Platinum"]
  },
  {
    _id: "show2",
    movie: "movie1",
    theater: "theater1",
    date: "2024-01-01",
    time: "1:30 PM",
    price: 18,
    pricePlatinum: 28,
    priceGold: 23,
    priceSilver: 18,
    availableSeats: [
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
    ],
    seatTiers: ["Silver", "Silver", "Gold", "Gold", "Platinum"]
  },
  {
    _id: "show3",
    movie: "movie2",
    theater: "theater2",
    date: "2024-01-01",
    time: "7:00 PM",
    price: 20,
    pricePlatinum: 30,
    priceGold: 25,
    priceSilver: 20,
    availableSeats: [
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
      [true, true, true, true, true, true, true, true],
    ],
    seatTiers: ["Silver", "Silver", "Gold", "Gold", "Platinum"]
  }
];

const mockUsers = [
  {
    _id: "admin1",
    name: "Admin User",
    email: "admin@cineverse.com",
    password: "admin123",
    role: "admin",
    favorites: [],
    recentlyViewed: [],
    bookingHistory: [],
    loyaltyPoints: 0
  },
  {
    _id: "user1",
    name: "Test User",
    email: "user@cineverse.com",
    password: "user123",
    role: "user",
    favorites: [],
    recentlyViewed: [],
    bookingHistory: [],
    loyaltyPoints: 250
  }
];

const mockBookings = [];

module.exports = { mockMovies, mockTheaters, mockShows, mockUsers, mockBookings };
